apache/druid-website-src

- downloads.md
In preparation for making the site more Apache, removing non-apache links from the download page as per Apache rules.
> Remove tranquility from download page

- google7061d72c536b2e8d.html
I wanted to investigate the SEO situation for the new https://druid.apache.org/ website using the Google Search Console: https://search.google.com/search-console/about. To do this, Google wants me to prove that I am affiliated with druid.apache.org by placing this HTML file at the web root.
> Add Google Search Console verification file.

- community/index.md
- community/join-slack.md
- Add link to ASF Slack
- Add link to Twitter account
- Add info about StackOverflow tags people can use to ask questions
- Remove link to IRC, it doesn't seem very popular anymore
> Community page updates.

- community/index.md
- community/join-slack.md
From ASF Infra channel:
Using `https://s.apache.org/slack-invite` directly
> Fix Slack link

- _includes/news-list.html
- _includes/page_footer.html
Fixes https://github.com/apache/druid/issues/9264 by removing the link from the footer
> remove direct download from footer, incubating cleanup

- druid-powered.md
Original URL was trying to redirect internally to "https://druid.apache.org/www.deep.bi" instead which doesn't exist, added "https://" and spacing to try and circumvent this.
> Fixed Deep.BI Broken Link

- libraries.md
Societe General developpers worked on a connector Druid for Grafana and added features in order to work with the latest version of Grafana
> Add reworked plugin Druid for Grafana

- libraries.md
I saw all the rest have a github page but assumed it wasn't a requirement since those github pages in many cases just redirected to the commercial link. If that's not the case please let me know!
> Added Deep.Explorer to the UIs section

- community/index.md
Slack invite link for druid channel no longer works. Those without an `@apache.org` address need an invitation from someone who is already in the ASF slack workplace.
> Add instructions on how to get druid slack channel invitation

- community/index.md
- community/join-slack.md
Update the universal `https://druid.apache.org/community/join-slack` invite link to point to the new Apache Druid Slack
> Shift the invite link to point to Apache Druid Slack

- robots.txt
Versions don't necessarily start with zero anymore!
We need these directives so search engines prefer indexing the "latest" URLs instead of version-specific URLs.
> Disallow versioned docs post-24.0.

- community/index.md
Removing link to Druid Forum from the community page.
> Remove DF from Community page

- _includes/event-list.html
Amends the iterator so that an event is only included if it's today or afterwards (bit of a hack without the time) - so only upcoming events are shown. Kicks out "nothing scheduled yet" if no events are relevant.
> Events - change to only show future events

- druid-powered.md
Bannerflow is no longer using Druid, so should be removed from the powered by page.
> Remove Bannerflow from druid-powered.md

- community/index.md
The link on the rendered site ends up dropping people on the index for the whole site  since it resolves to `https://druid.apache.org/docs//`, which isn't that helpful IMO.
The intent of the logic seems to be to drop someone on the docs index page for most recent stable version, so it makes sense to replace it with `latest`.
> change the link to point to the actual latest docs

- README.md
- scripts/do_all_things.py
Use the `--no-docs` flag if you want to use the publish script to update the site (e.g., home page) without any change in the documentation
Example:
```
python do_all_things.py -v 27.0.0 --no-docs
```
> Add publishing option for updating site without docs

- src/pages/index.js
https://github.com/apache/druid-website-src/pull/413 actually already fixed the redirect file just in case. This PR just goes back to using it.
> switch the button back to a redirect

- package-lock.json
- scripts/build_docs.py
- scripts/copy_druid_docs.py
- yarn.lock
We were using shutil's copy before, which left us with orphan files.
* Copy script now uses `rsync --delete` for the Markdown files so that we always have only the Markdown files from `apache/druid`
* Build now deletes the `published_versions/docs/VERSION` destination folder before hand so that we end up with HTML files that match the Markdown files being used as the source
> update build and copy scripts to account for deleted files

- src/pages/downloads.mdx
There is no separate Hadoop 3 build for the 27 release.
> Remove reference to Hadoop 3 download link

- README.md
- scripts/build_docs.py
- scripts/do_all_things.py
Docusaurus 2 assigns an alphanumeric string to all assets, unlike Docusaurus 1, which kept the filename as is. Example: https://druid.apache.org/assets/images/druid-architecture-c89f21addd50d76d07dbc3a730cd856f.png
That means we can't re-publish a previous version of the docs without having the associated assets. This PR updates the build script to save the assets for all versions built.
Tested locally with the following command:
```
python do_all_things.py -v 28.0.0 --source ../../druid-apache
```
> Update build scripts to save assets for all versions

- src/pages/community/join-slack.md
This expires after every 400 shares. When this happens, follow these instructions:
Anyone can currently create an invite link via:
Apache Druid -> Invite people to Apache Druid
However, the link has to be limited by either time and/or amount of people. Before pressing Copy invite link, first click on Edit link settings, where you can set the link expiry to "Never expire".
Then click the "Copy invite link" and use it to update the website.
> Renew the public invite for Slack

- static/js/RecentReleasesWidget.js
- static/js/version.js
This PR changes the code in RecentReleasesWidget.js to show the three most recent releases. The PR also adds the Druid 28.0.0 release to the version.js file.
> Update releases widget

- scripts/copy_druid_docs.py
The script falls on its face if the directory doesn't exist. But if it doesn't exist, we don't need to delete it 🍤
> script: add if statement for delete so that the script doesnt fail

- src/css/base.css
Apache infra does not like an external reference to an img, so the background doesn't show up on the staging site/prod site
> fix: change external img to just color in css

- src/pages/index.js
Add a 'Security' link to the homepage pointing to the Druid-specific security overview page, which contains relevant information about the Druid security trust model, and also contains the information on how to report security issues. Remove the link to the generic Apache-wide security page, as that is linked from the Druid-specific one.
> Link to Druid-specific security page

- scripts/copy_druid_docs.py
Docusaurus 3 uses MDXv3, which is much stricter.
The longstanding way we've done variables is to find/replace `{{DRUIDVERSION}}` in the Markdown files. It worked in 2 b/c 2 was less strict. 3 is stricter and picks them up as Javascript variables that are undefined. 
Instead of making people learn a new way to do variables, this updates the copy script so that an escaped version of `\{\{DRUIDVERSION}}` (and variations) also get find/replaced
We would have to do a find/replace anyway unless we set up the variables to match each other in `druid-website-src` and `druid`
To verify this, check out the Markdown cleanup branch in https://github.com/apache/druid/pull/17740 and run the copy script in `scripts`.
Then grep for `DRUIDVERSION` in the markdown files and maybe whatever version you set, …
> infra: update copy druid script

- src/pages/libraries.md
Hi Apache team,
At redBorder, we developed rb-druid-indexer as one of our internal services. The idea is to simplify indexing task submissions in distributed systems. rb-druid-indexer functions as a cluster-compatible service that manages indexing tasks. It also load-balances task submissions and deletions to the Druid router(s) and includes failover capabilities using ZooKeeper for coordination.
Currently, rb-druid-indexer supports multiple Kafka brokers, custom field dimensions, load balancing across Druid routers, excluded dimensions, and several other useful features. You can configure rb-druid-indexer using a YAML file like the example below:
```
zookeeper_servers:
- "rb-malvarez1.node:2181"
- "rb-malvarez3.node:2181"
- "rb-malvarez2.node:2181"
tasks:
- task_name: "rb_monitor"
feed: …
```
> Add rb-druid-indexer to /src/pages/libraries.md & fix broken link
