apache/druid-website-src

_includes/page_footer.html
scss/footer.scss

Also make the copyright stuff have explicit line breaks

Update footer text

---

docs/0.15.0-incubating/development/extensions-contrib/orc.html
docs/latest/development/extensions-contrib/orc.html

Redirect path should be relative.

Fix wrong redirect for orc

---

docs/0.15.0-incubating/operations/recommendations.md
docs/0.15.0-incubating/toc.md
docs/latest/operations/recommendations.md
docs/latest/toc.md

Missing doc backports for 0.15.0-incubating

Doc backports 7992 and 7993

---

druid-powered.md

We use druid for real-time video enablement analytics.

Added CircleHD

---

druid-powered.md

add oppo usage of druid in  druid-powered.md

Update druid-powered.md 

---

druid-powered.md

Please include the changes to the 'Powered By' page regarding the Millersoft aspect.

Adding Millersoft to the 'Powered By' page

---

druid-powered.md

Adding new links related to Nielsen's work with Druid, and removing an old one

Updating Nielsen's resources in powered-by page

---

_data/featured.yml

A new blog post by Nielsen covering data retention and data deletion

Added Nielsen blog post

---

community/index.md

Ref: https://lists.apache.org/thread.html/25608cb9e0dc4af7bca4af36371b66747f835343ad7c4b910d73d76c@%3Cdev.druid.apache.org%3E

adding vogievetsky to committer list

---

community/index.md

See thread at https://lists.apache.org/thread.html/2fce3901ed8ab52e20d01849ea40ac0163e784c942f376fbe24467a3@%3Cdev.druid.apache.org%3E.

Update Starter issues link.

---

community/cla.md
community/index.md

Update the community & CLA pages to reflect Apache policy.

Clarify CLA policy.

---

druid-powered.md

Remove broken urls:
* https://jini.site/jin-yumafengwobig-data-in-travel-real-time-analytics-with-kafka-spark-and-druid_269053
* http://liquidm.com/reporting-at-liquidm/

Remove broken urls

---

libraries.md

Added level23/druid-client PHP package

Update libraries.md - Added level23/druid-client PHP package

---

libraries.md

Also sorted the list alphabetically

Add HDP to druid distributions list

---

docs/0.16.0-incubating/tutorials/cluster.html
docs/0.16.0-incubating/tutorials/index.html

Update 0.16.0 docs with https://github.com/apache/incubator-druid/pull/9008

Backport Docs: bold Java 8 requirement #9008

---

docs/latest/tutorials/cluster.html
docs/latest/tutorials/index.html

Backport https://github.com/apache/incubator-druid/pull/9008, update the `latest` directory as well

Backport 9008, add latest docs

---

CONTRIBUTING.md
README.md
downloads.md
druid-powered.md
index.html
libraries.md
licensing.md
package.json
release.sh

This PR updates links to the old incubator repos and download links to the post-graduation versions.

Update incubation repo references, use new download links

---

druid-powered.md

Since Trendyol started to use Druid in production. We wanted to add it to the list.

Add Trendyol to powered list

---

druid-powered.md

Added Nodex to the "Powered by" list

Adding a new site to the list

---

druid-powered.md

Hello, thank you for your consideration! The phrasing I have put in there might have been better in terms of making it clear but the main point is that our platform is built on Druid (on which our UI platform is built as well) as the core with others such as Flink and Cassandra that allow us to augment the way we use Druid.
Thanks in advance!

Update Added Deep.BI

---

_data/featured.yml

update featured content

---

community/index.md

update community page

---

druid-powered.md

added https://speakerdeck.com/druidio/analytics-at-wikipedia-with-druid

update wikimedia foundation powered by

---

_data/events.yml

1. Big Things Virtual Meetup
2. Druid Summit

Updating upcoming events

---

_data/events.yml
druid-powered.md

update events and poweredby pages

---

_data/events.yml

update events 07/27/2020

---

index.html

fix typo on index.html

---

druid-powered.md

add superawesome and ibotta

---

druid-powered.md

added Razorpay, Sage+Archer, SuperAwesome linked talk, and Dream 11 linked talk

add to powered by

---

druid-powered.md

added swisscom, moved shoppee to proper alphabetical order

add swisscom

---

community/index.md

Also make "GitHub pull requests" a link so it is easier to contributors to find it.

Add a section about automated testing of Pull Requests

---

community/index.md

Fix the link to the list of issues suitable for new developers.

---

data/example-manifests-v2.tsv

This is the next version of this file: https://github.com/apache/druid-website-src/blob/master/data/example-manifests.tsv but with the starter example spec upgraded to not use firehoses and also to not hard code the name as `new_data_source`
This is in support of https://github.com/apache/druid/pull/10787

new example manifest

---

druid-powered.md

As a maintainer of SigNoz, I would like to request adding SigNoz as a user of Druid.

Add SigNoz to druid-powered.md

---

community/index.md

Update company affiliation

---

druid-powered.md

Updated the following entries with links: Airbnb, Avesta, GameAnalytics, Sage + Archer

Added links to existing entries

---

druid-powered.md

Add Flipkart, Play Games24x7, Preset, Shopify, Lohika, Scalac, CrunchMetrics & Trustpilot

Add 8 new PoweredBy entries

---

community/index.md

Added Druid Forum (by Imply) to the list.

Add Druid Forum (by Imply) to community channels list

---

druid-powered.md

Also, fix spacing issue in Hawk.

Add ironSource, WhyLabs & Hexaglobe

---

_data/featured.yml

Adding posts by Hellmar Becker

New featured articles for Mar 2022

---

_data/events.yml

Refresh events

---

CONTRIBUTING.md

Link update to https://github.com/apache/druid/tree/master/docs

Docs - docs link update

---

_config.yml

this config determines what latest releases we show on index page.

Remove old release from _config.yml

---

druid-powered.md

More accurately reflects the software that druid is used on rather than blanket across our products

Update to Nodex powered by

---

community/index.md

Adding LinkedIn to the "other" places people can meet the community.

Add LI to community list

---

_data/events.yml

March events added, removed old ones.

202302-marchEvents

---

_data/events.yml

20230327 - Featured events update

---

druid-powered.md

Hi, I'm the CTO for TelemetryDeck and would like to add our company to the list of companies using Druid <3

Adding TelemetryDeck to druid-powered.md

---

community/index.md

Updating index.md with current org.

Updating index.md with current org

---

libraries.md

Update Apache Superset in libraries.md

Update libraries.md Apache Superset

---

index.html

Added a temporary druid.NEXT event promotion banner. Please review and let me know if you have any questions. Screenshots attached below for reference:

druid.NEXT promotion banner

---

index.html

Revert "druid.NEXT promotion banner"

---

docusaurus.config.js
package-lock.json
package.json
yarn.lock

adds a local search for Druid in case something goes wrong with Algolia on prod using this plugin: https://github.com/praveenn77/docusaurus-lunr-search
Here it is deployed on a Netlify preview: https://deploy-preview-11--frabjous-kulfi-9f6ae5.netlify.app/

add lunr search

---

static/js/FeatureList.js

This adds another row of Druid key features on the home page of druid.apache.org
Preview on localhost below:

Updated feature list on Home page

---

src/pages/community/index.mdx

This PR:
- Adds two links to the Druid Community page

Add links to Druid Community page

---

src/pages/downloads.mdx

This PR changes the release version in the Older releases section.

Fix older releases version

---

static/js/FeaturedContent.js

@317brian @petermarshallio please review

Add upsert blog to featured list

---

src/pages/community/join-slack.md

New Slack invite link.

---

src/pages/community/index.mdx

It isn't immediately obvious how to subscribe to the dev list.

Add info about how to subscribe to the dev list.

---

src/pages/druid-powered.md

"Hey Hugh, not sure if a Peter spoke to you but can you add Spideo to powered by page and link this blog. It is a good one. https://spideo.com/business/introducing-connect-personalization-at-scale/"

Add a powered by entry for Spideo as requested by Tom Mack

---

static/js/FeaturedContent.js

Add Hellmar's September blog to the featured content list

Add new blog to FeaturedContent.js

---

src/pages/community/join-slack.md

Updated the community page with a fresh Slack invitation link.

Updating slack invite link.

---

src/pages/libraries.md

Hi team,
I built an mcp-server for druid. I previously raised a PR to druid official repo. They have asked me to keep the mcp server separate repo and raise a PR here to list it on this page.
Thanks,
Anil
@317brian

Update libraries.md. 

---

src/pages/community/join-slack.md

refresh slack link

---

docs/34.0.0/release-info/release-notes.md
docs/latest/release-info/release-notes.md

fix: fix whitespace

---

src/pages/druid-powered.md

Hi, I’m a DevOps Engineer at adjoe, and we’d like to add our company to the list of organizations using Druid.
Thank you for building and maintaining such a great tool!

Add adjoe to druid-powered.md
